name: Australia

shortcode: australia # australia australia?
year: 2022
city: Melbourne
local_area: Australia
area: Australia
area_adj: Australian
tz: AEDT
email: australia@writethedocs.org
color: green
rgb: 61, 217, 74
hex: 3dd94a
time_format: 12h

photos:
  default: _static/conf/images/headers/WTDHeader.png

buttons:
  top:
    # - text: Welcome to our conference
    #   link: /news/welcome
    # - text: Sponsor us
    #   link: /sponsors/prospectus
    # - text: Submit a Talk
    #   link: /cfp
    # - text: Date and ticket information
    #   link: /news/announcing-virtual-conf-dates-tickets
    # - text: Read our conference guide
    #   link: /welcome-wagon
    # - text: See the Schedule!
    #   link: /schedule
     - text: Buy a Ticket!
       link: /tickets
     - text: See the talks!
       link: /speakers
 #    - text: See the Schedule!
 #      link: /schedule
 #    - text: Read our guide
 #      link: /welcome-wagon
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ
  bottom:
  #   - text: Welcome to our conference
  #     link: /news/welcome
     - text: Sponsor the conference
       link: /sponsors/prospectus
    # - text: Submit a Talk
    #   link: /cfp
    # - text: See the Schedule!
    #   link: /schedule
    # - text: Date and ticket information
    #   link: /news/announcing-virtual-conf-dates-tickets
    # - text: See the talks!
    #   link: /speakers
     - text: Buy a Ticket!
       link: /tickets
 #    - text: Read our guide
 #      link: /welcome-wagon
 #    - text: See the schedule!
 #      link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ

tickets:
  corporate:
    price: $175
  independent:
    price: $100
  student:
    price: $25

sponsorship:
  first_draft:
    price: AUD $1,000
  second_draft:
    price: AUD $2,000
  publisher:
    price: AUD $4,000
  patron:
    price: AUD $7,000
  keystone:
    price: AUD $10,000

date: # how do we handle these? human readable would be nice.
  main: "**December 8-9, 2022**"
  short: Dec 8-9, 2022
  tickets_live: "July 2022"
  month: December

  # Conference is special for the index to show the combined conference days
  # conference:
    # event: Main Conference
    # date: Dec 8-9
    # summary: The main days of the conference. We will be running one main track, as well as <a href="/conf/australia/2022/lightning-talks/">Lightning Talks</a> & <a href="/conf/australia/2022/unconference/">Unconference</a>.
    # icon: conference

  # These are listed in the schedule
  day_one:
    event: Conference Day 1
    date: December 8
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Thursday
    talk_time: 09:30-16:30
    unconference_time: 13:30-15:30
    icon: conference
  day_two:
    event: Conference Day 2
    date: December 9
    summary: And the conference goes on! We are already starting to miss you.
    dotw: Friday
    talk_time: 09:30-16:45
    unconference_time: 13:30-15:30
    icon: conference
  total_talk_days: 2

about:
  attendees: 150
  summary:
    "The main presentation track takes place during **December 8-9 (Thursday and Friday) from 10:00am to 4:00pm AEDT**.
    During the main event we also run an :doc:`/conf/australia/2022/unconference`."

  social_venue: Spatial chat platform
  venue:
    "Online, https://hopin.to/. Your login will be emailed to you before the event"
  photos:
  mainroom: "Video area"
  unconfroom: "Chat area"
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"

cfp:
  url: https://pretalx.com/wtd-australia-2022/cfp
  ends: "September 16, 2022"           # 2 weeks to review and get confirmations
  notification: "September 30, 2022"   # leaves 8 weeks to write and record
  video_by: "November 7, 2022"   # 4 weeks before the conf

grants:
  url: https://docs.google.com/forms/d/e/1FAIpQLSfZczqqIwuz8Gj57O5MsJrPqW-K195bqD1-LovRw-dF_d4z5A/viewform
  ends: "October 15, 2022"
  notification: "October 31, 2022"


sponsors:
  keystone:
  patron:
  publisher:
    - name: atlassian
      link: https://www.atlassian.com/
      brand: Atlassian
      width: 550px
  second:
    - name: knowledgeowl
      link: https://www.knowledgeowl.com
      brand: KnowledgeOwl
      width: 250px
      text: "<p>KnowledgeOwl makes knowledge base software. We value excellent customer support and service-driven ethical business practices.</p> <p>KnowledgeOwl​ is looking for more contributors for our ​company blog​. This is an opportunity to write about a topic that interests you and get paid for it :)</p> <p>KnowledgeOwl also sponsors and hosts The Not-Boring Tech Writer podcast. We are always looking for new guests to share their stories, experience, and expertise with the world.</p> <p>Feel free to stop by and ask us more about KnowledgeOwl, these opportunities, or anything else!</p>"
  first:
  in_kind:
    - name: rtd
      link: https://readthedocs.com/
      brand: Read the Docs


unconf:
  url: http://bit.ly/wtd-au-2022-ro

# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: False
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: True
flagrunofshow: False
flaghasschedule: True
flaghasunconf: False
flaghasshirts: True
flagvideos: False
flaglivestreaming: False
flagpostconf: False
flagcancelled: False

# Truthy things that don't change
flaghashike: False
flaghasfood: False
flaghasboat: False
flaghaswritingday: True
flaghasjobfair: False
flaghasbadgeflair: False
