name: Australia

shortcode: australia # prague australia?
year: 2024
city: Melbourne
local_area: Australia
area: Australia
area_adj: Australian
tz: AEDT
email: australia@writethedocs.org
color: blue
rgb: 74, 193, 224
hex: 4AC1E0
time_format: 12h

photos:
  default: _static/conf/images/headers/atlantic-group.png

buttons:
  top:
  #   - text: Read our latest news
  #     link: /news/welcome
  #   - text: Sponsor us
  #     link: /sponsors/prospectus
  #  - text: Submit a Talk
  #    link: /cfp
  #   - text: Date and ticket information
  #     link: /news/announcing-virtual-conf-dates-tickets
  #   - text: Read our conference guide
  #     link: /welcome-wagon
  #   - text: See the Schedule!
  #     link: /schedule
  #  - text: Buy a Ticket!
  #    link: /tickets
  #  - text: See the talks!
  #    link: /speakers
  #  - text: See the Schedule!
  #    link: /schedule
  #  - text: Read our guide
  #    link: /welcome-wagon
  #  - text: Watch the Live Stream
  #    link: /livestream
  #  - text: Watch the videos!
  #    link_absolute: https://www.youtube.com/playlist?list=PLy70RNJ7dYrJR66QtoHmTWSqm4iAlmH-m
  #  - text: Thanks for coming
  #    link: /news/thanks-recap
  bottom:
  #   - text: Welcome to our conference
  #     link: /news/welcome
  #   - text: Sponsor the conference
  #     link: /sponsors/prospectus
  #   - text: Submit a Talk
  #     link: /cfp
  #   - text: See the Schedule!
  #     link: /schedule
  #   - text: Date and ticket information
  #     link: /news/announcing-virtual-conf-dates-tickets
  #   - text: See the talks!
  #     link: /speakers
  #   - text: Buy a Ticket!
  #     link: /tickets
  #   - text: Read our guide
  #     link: /welcome-wagon
  #   - text: See the schedule!
  #     link: /schedule
  #    - text: Watch the Live Stream
  #     link: /livestream
  #   - text: Browse the photos
  #     link_absolute: https://www.flickr.com/photos/writethedocs/albums/72177720313823452/
  #   - text: Watch the videos!
  #     link_absolute: https://www.youtube.com/playlist?list=PLy70RNJ7dYrJR66QtoHmTWSqm4iAlmH-m

tickets:
  corporate:
    price: $300
  independent:
    price: $250
  student:
    price: $100

sponsorship:
  first_draft:
    price: $1,500
  second_draft:
    price: $2,500
  publisher:
    price: $5,000
  patron:
    price: $8,500
  keystone:
    price: $13,500

shirts:
  url: https://teespring.com/wtd-pdx-2023
  ends: "Dec 31, 2023"

date: # how do we handle these? human readable would be nice.
  main: "**November 28-29, 2024**"
  short: Nov 28-29, 2024
  tickets_live: "July 2024"
  month: November
  # Conference is special for the index to show the combined conference days
  conference:
    event: Main Conference
    date: November 28-29
    summary: The main days of the conference. We will be running one main track, and an <a href="/conf/australia/2024/unconference/">Unconference</a>.
    icon: conference

#    summary: The main days of the conference. We will be running one main track, and an Unconference.
  # These are listed in the schedule
  day_one:
    event: Outing
    date: On your own or community-sourced
    summary: If you are in town early, we encourage you to go exploring one of the most liveable cities in the world, Melbourne.
    icon: hike
    dotw: Wednesday
  day_two:
    event: Conference Day 1
    date: November 28
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Thursday
    talk_time: 09:30-16:30
    unconference_time: 11:00-15:00
    social_time: 17:00pm-19:00pm
    icon: conference
  day_three:
    event: Conference Day 2
    date: November 29
    summary: And the conference goes on! We are already starting to miss you. |:heart:|
    dotw: Friday
    talk_time: 09:30-16:00
    unconference_time: 11:00-15:00
    icon: conversation
  total_talk_days: 2

about:
  attendees: 100
  summary:
    "The main presentation track takes place during **November 28-29 (Thursday and Friday) from 9:30am to 4:30pm AEDT**.
    During the main event we also run an :doc:`/conf/australia/2024/unconference`."

  social_venue: TBA
  venue: TBA
  photos: TBD
  mainroom: TBA
  unconfroom: TBA
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"

cfp:
  url: https://pretalx.com/wtd-australia-2023/cfp # Open July 15, 2023, 8 weeks to submit
  ends: "September 22, 2023"           # 2 weeks to review and get confirmations
  notification: "September 30, 2023"   # 8 weeks to write and prepare
  slides_by: "December 01, 2023"       # 1 week before
  preview: "TODO"                      # Preview URL TODO

unconf:
  url: https://bit.ly/wtd-au-2023
  date: "Thursday and Friday after the morning tea break"


grants:
  url: https://forms.gle/Pi7zm72XPjebNzS16
  ends: "October 15, 2023"
  notification: "October 31, 2023"


sponsors:
  keystone:
  patron:
  publisher:
  #  - name: atlassian
  #    link: https://www.atlassian.com/
  #    brand: Atlassian
  #    width: 750px
  #  - name: knowledgeowl
  #    link: https://www.knowledgeowl.com
  #    brand: KnowledgeOwl
  #   width: 450px
  #    text: "<p>KnowledgeOwl makes knowledge base software. We value excellent customer support and service-driven ethical business practices.</p> <p>KnowledgeOwl​ is looking for more contributors for our ​company blog​. This is an opportunity to write about a topic that interests you and get paid for it :)</p> <p>KnowledgeOwl also sponsors and hosts The Not-Boring Tech Writer podcast. We are always looking for new guests to share their stories, experience, and expertise with the world.</p> <p>Feel free to stop by and ask us more about KnowledgeOwl, these opportunities, or anything else!</p>"
  second:
  first:
  in_kind:
    - name: rtd
      link: https://readthedocs.com/
      brand: Read the Docs

# Things that change over time, listed in order of change
flaglanding: True
flaghassponsors: False
flagcfp: False
flagticketsonsale: False
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flaghasunconf: False
flaghasshirts: False
flagvideos: False
flaglivestreaming: False
flagpostconf: False
flagcancelled: False

# Truthy things that don't change
flaghashike: False
flaghasfood: True
flaghasboat: False
flaghaswritingday: False
flaghasjobfair: False
flaghasbadgeflair: False
