name: Berlin
shortcode: berlin
year: 2025
city: Berlin
local_area: Germany
area: Europe # European Australian
area_adj: European
tz: CET  # PT until March, PST after... :/
email: berlin@writethedocs.org
color: green
rgb: 61, 217, 74
hex: 3dd94a
time_format: 24h

photos:
  default:
    - _static/conf/images/headers/2025/grants.jpg
    - _static/conf/images/headers/2025/unconference.jpg
    - _static/conf/images/headers/2025/volunteer.jpg
    - _static/conf/images/headers/2025/writing-day.jpg
  index:
    - _static/conf/images/pics/writing-day.jpg
    - _static/conf/images/pics/reg.jpg

buttons:
  top:
    # - text: Conference announcement
    #   link: /news/welcome
    # - text: Sponsor us
    #   link: /sponsors/prospectus
    # - text: Submit a Talk
    #   link: /cfp
#     - text: See the Schedule
#       link: /schedule
    #  - text: See the Speakers
    #    link: /speakers
#     - text: Buy a Ticket
#       link: /tickets
    # - text: Attendee Guide
    #   link: /attendee-guide
    # - text: Watch the Live Stream
    #   link: /livestream
     - text: Watch the videos
       link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpm4FboYSTD1Bs8Yp8k_JvAL
     - text: Conference recap
       link: /news/thanks-recap
  bottom:
    #  - text: Conference announcement
    #    link: /news/welcome
    # - text: Sponsor us
    #   link: /sponsors/prospectus
    # - text: Submit a Talk
    #   link: /cfp
    # - text: Buy a Ticket!
    #   link: /tickets
#    - text: See the Schedule
#      link: /schedule
    #  - text: See the Talks
    #    link: /speakers
#    - text: Read the Guide
#      link: /attendee-guide
    # - text: Watch the Live Stream
    #   link: /livestream
#     - text: Conference recap
#       link: /news/thanks-recap
     - text: Browse the photos
       link_absolute: https://www.flickr.com/photos/writethedocs/albums/72177720329921230
     - text: Watch the videos!
       link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpm4FboYSTD1Bs8Yp8k_JvAL

tickets:
  concierge:
    price: €575
  corporate:
    price: €475
  independent:
    price: €275
  student:
    price: €75
  virtual_corporate:
    price: €140
  virtual_independent:
    price: €75
  virtual_student:
    price: €30
#  button: >
#    .. raw:: html
#
#      <p style="margin: 2em 0;">
#      <table border="0" cellpadding="0" cellspacing="0" style="background-color:#2ECC71; border:1px solid #4a4a4a; border-radius:5px;">
#      <tr>
#          <td align="center" valign="middle" style="color:#FFFFFF; font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; letter-spacing:-.5px; line-height:150%; padding-top:15px; padding-right:30px; padding-bottom:15px; padding-left:30px;">
#            <a href="https://ti.to/writethedocs/write-the-docs-portland-2025/" target="_blank" style="color:#FFFFFF; text-decoration:none; border-bottom: none;">Get your ticket</a>
#          </td>
#      </tr>
#      </table>
#      </p>

sponsorship:
  second_draft:
    price: €2,000
  publisher:
    price: €3,500
  patron:
    price: €5,500
  keystone:
    price: "" # None to not render

grants:
 url: https://docs.google.com/forms/d/e/1FAIpQLSdvTwk29nEHRnXhzwF-TX4mSCbtBXxo7qOPcwGQugCar6ocZg/viewform
 ends: 'August 1, 2025, 23:59 CET'
 notification: 'August 20, 2025'
#
shirts:
  url: https://shirt.writethedocs.org/
  ends: "November 31, 2025"

date: # how do we handle these? human readable would be nice.
  main: "**Oct 27-28, 2025**"
  short: Oct 27-28, 2025
  tickets_live: "June 2025"
  month: October

  # Conference is special for the index to show the combined conference days
  conference:
    event: Speaker Talks
    date: October 27-28
    summary: The main days of the conference. Listen to a diverse panel of speakers share their insights and experience.
    icon: conference

  # These are listed in the schedule
#  day_one:
#    event: Hike
#    date: May 3
#    # summary: We encourage you to go on a hike in your own beautiful home town.
#    summary: If you're in town early, join us for the Hike. Portland has excellent access to the woods right in the city.
#    icon: hike
#    dotw: Saturday
#  day_two:
#    event: Writing Day
#    date: May 4
#    summary: Kick off the conference with Writing Day and work with fellow documentarians on a project. Followed by the opening reception.
#    icon: writing
#    dotw: Sunday
#    writing_day_time: 9am-5pm
#    reception_time: 5-7pm
  day_one:
    event: Conference Day 1
    date: October 27
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Monday
    talk_time: 10:00-17:00
    unconference_time: 10:45-17:00
    social_time: 19:00-21:00
    icon: conference
  day_two:
    event: Conference Day 2
    date: October 28
    summary: And the conference goes on! More talks and unconference today!
    dotw: Tuesday
    talk_time: 10:00-17:00
    unconference_time: 13:00-17:00
    icon: conversation
  total_talk_days: 2

about:
  attendees: 200
  social_venue: NEST, Görlitzer Str. 52, 10997 Berlin
  venue: bUm Berlin
  venue_address: Paul-Lincke-Ufer 21, 10999 Berlin
  photos: https://www.flickr.com/photos/writethedocs/albums/72177720329921230
  mainroom: Main stage
  unconfroom: TBC
  projector_ratio: "16:9"

cfp: # Conf dates 27-28 October
  url: "https://pretalx.com/wtd-berlin-2025/cfp"   # Open June 2 (Mon), -> 8 weeks to submit
  ends: "August 4, 2025"                           # (Mon) 1 week, to review. It'll take a little longer to announce
  confirm_by: "August 15, 2025"
  notification: "August 18, 2025"                  # (Mon) 8 weeks to write and prepare
  speaker_tickets_by: October 6, 2025              # (Mon) Approx 3 weeks before
  video_by: October 6, 2025                        # Only 1 so...
  slides_by: "October 20, 2025"                    # (Mon) 1 week before
  preview: "TODO"                                  # Preview URL TODO

lightning_talks:
  signup_url: https://docs.google.com/forms/d/e/1FAIpQLSdTGBDgbgeyxIMQ8tLo1TRlZ3dKirc1cJuMarVe1eYIRKnWrw/viewform

qa:
  event_id: 2SsaJyxrDcyAS8YigHQzCn

unconf:
  url: https://docs.google.com/spreadsheets/d/11O2NRC3mQRIdH44OGgjSil3Y6YqpBIfvKqvVTYAsacQ/edit?usp=sharing
  date: "All day, Monday, October 27 and Tuesday, October 28"

#writing_day:
#  url: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSeHMZ1uXTfnT0HMm-KfsgxYV1w3tmS7bMPtBx4H9cktJpSrdg/viewform?usp=dialog"
#  date: Sunday, May 4, 9 AM - 5 PM

#hike:
#  date: Saturday, May 3, 2 PM

sponsors:
  keystone:
  patron:
    - name: kapa-ai
      link: https://www.kapa.ai/?ref=writethedocs
      brand: Kapa.ai
    - name: paligo-new-new
      link: https://paligo.net?utm_source=write_the_docs_berlin_2025&utm_medium=sponsored_conference
      brand: Paligo
    - name: archbee-new-new
      link: https://www.archbee.com/?ref=writethedocs
      brand: Archbee
    - name: gitbook
      link: https://www.gitbook.com/?ref=writethedocs
      brand: GitBook
  publisher:
  second:
    - name: discourse
      link: https://discourse.org/pricing?ref=writethedocs
      brand: Discourse
    - name: knowledgeowl
      brand: KnowledgeOwl
      link: https://www.knowledgeowl.com?ref=writethedocs
      width: 250px
    - name: fern
      brand: Fern
      link: https://buildwithfern.com/?ref=writethedocs
  first:
  in_kind:
    - name: readthedocs
      link: https://about.readthedocs.com/?ref=writethedocs
      brand: Read the Docs
      text: "Read the Docs simplifies software documentation by building, versioning, and hosting of your docs, automatically. Treating documentation like code keeps your team in the same tools, and your documentation up to date."
# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: False
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: True
flagrunofshow: False
flaghasschedule: True
flagscheduleincomplete: False
flaghasshirts: False
flaglivestreaming: False
flagvideos: False
flagpostconf: True
flaghasbadgeflair: False

# Truthy things that don't change
flaghasunconf: True
flaghashike: False
flaghasfood: True
flaghaswritingday: False
flaghaslightningtalks: True
flaghasjobfair: False
flaghasboat: False
