name: Portland

shortcode: portland # prague australia?
templatecode: na # HACK
year: 2018
city: Portland
area: North American # European Australian
tz: PST
email: portland@writethedocs.org

tickets:
  community:
    price: 750
  corporate:
    price: 450
  independent:
    price: 250
  student:
    price: 250

date: # how do we handle these? human readable would be nice.
  main: "**May 6-8, 2018, in Portland, Oregon**"
  tickets_live: "January 2018"
  month: May
  sat: 5

about:
  summary:
    "The main presentation track takes place from **May 7-8 (Monday and Tuesday) from 9am to 6pm**.
    We will return to the historic `Crystal Ballroom <http://www.mcmenamins.com/CrystalBallroom>`_, `centrally located <http://goo.gl/maps/D2WrJ>`_ in the heart of Portland.
    During the main event we also run an :doc:`/conf/portland/2018/unconference` downstairs in Lola's Room.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/portland/2018/venue` page."
  location:
    "Crystal Ballroom located at 1332 W Burnside St"

cfp:
  url: https://docs.google.com/forms/d/e/1FAIpQLSdb-MNRT3TdDTuVIcf-3lZRWDOgguZfjatLr-HLN5ngx5t04w/viewform
  ends: "January 10, 2018"
  notification: "end of January"


flagspeakersannounced: True
flagcfp: False
flaghasschedule: True
flagticketsonsale: False
flaghashike: True
flaghasboat: False
flaghasshirts: True
