name: Portland

shortcode: portland # prague australia?
templatecode: na # HACK
year: 2019
city: Portland
local_area: Oregon
area: North America # European Australian
area_adj: North American
tz: PST
email: portland@writethedocs.org
color: coral

photos:
  default: _static/2019/assets/headers/group.png

tickets:
  community:
    price: $800
  corporate:
    price: $500
  independent:
    price: $275
  student:
    price: $100

sponsorship:
  first_draft:
    price: $800
  second_draft:
    price: $2,000
  publisher:
    price: $4,500
  patron:
    price: $8,500
  keystone:
    price: $15,000

date: # how do we handle these? human readable would be nice.
  main: "**May 19-21, 2019, in Portland, Oregon**"
  short: May 19-21, 2019
  tickets_live: "January 2019"
  month: May
  day_one:
    event: Hike
    date: May 18
    summary: If you're in town early, join us for the <a href="/conf/portland/2019/hike/">Hike</a>. Portland has excellent access to the woods right in the city, and we'll be exploring Forest Park and the Hoyt Arboretum.
    icon: hike
  day_two:
    event: Writing Day
    date: May 19
    summary: Join us for the <a href="/conf/portland/2019/writing-day/">Writing Day</a> and Welcome Reception. The first official day of the conference is full of chances to interact with other documentarians.
    icon: writing
  day_three:
    event: Main Conference
    date: May 20-21
    summary: The main days of the conference. We will be running our main track in the ballroom, and the <a href="/conf/portland/2019/unconference/">Unconference</a> in Lola's Room.
    icon: conference

about:
  attendees: 500
  summary:
    "The main presentation track takes place from **May 20-21 (Monday and Tuesday) from 9am to 6pm**.
    We will return to the historic `Crystal Ballroom <http://www.mcmenamins.com/CrystalBallroom>`_, `centrally located <http://goo.gl/maps/D2WrJ>`_ in the heart of Portland.
    During the main event we also run an :doc:`/conf/portland/2019/unconference` downstairs in Lola's Room.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/portland/2019/venue` page."
  location:
    "Crystal Ballroom located at 1332 W Burnside St"

cfp:
  url: https://docs.google.com/forms/d/e/1FAIpQLScCK5qIaRwmn2UouYvtxfrQk56r_X72aliVWLnoGKb69HZuug/viewform

  ends: "17 January, 2019"
  notification: "8 February, 2019"

flaghashike: True
flaglanding: False
flagspeakersannounced: False
flagcfp: True
flaghasschedule: False
flagticketsonsale: True
flaghasboat: False
flaghasshirts: False
flaghassponsors: True
flagvideos: False
flaglivestreaming: False
