name: Portland

shortcode: portland # prague australia?
templatecode: na # HACK
year: 2019
city: Portland
local_area: Oregon
area: North America # European Australian
area_adj: North American
tz: PST
email: portland@writethedocs.org
color: coral

photos:
  default: _static/conf/images/headers/group.png

buttons:
  top:
    # - text: Sponsor the conference
    #  link: /sponsors/prospectus
    # - text: Submit a Talk
    #  link: /cfp
    # - text: Buy a Ticket!
    #   link: /tickets
    # - text: See the talks!
    #   link: /speakers
#    - text: See the Schedule!
#      link: /schedule
    # - text: Welcome Wagon
    #   link: /welcome-wagon
#    - text: Watch the Live Stream
#      link: /livestream
    - text: Browse the photos
      link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    - text: Watch the videos!
      link_absolute: /videos/portland/2019
  bottom:
    # - text: Sponsor the conference
    #  link: /sponsors/prospectus
    # - text: Submit a Talk
    #  link: /cfp
    # - text: Buy a Ticket!
    #   link: /tickets
#    - text: Prepare with the Welcome Wagon
#      link: /welcome-wagon
#    - text: See the schedule!
#      link: /schedule
    # - text: Watch the Live Stream
    #  link: /livestream
    - text: Browse the photos
      link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    - text: Watch the videos!
      link_absolute: /videos/portland/2019

tickets:
  community:
    price: $800
  corporate:
    price: $500
  independent:
    price: $275
  student:
    price: $100

sponsorship:
  first_draft:
    price: $800
  second_draft:
    price: $2,000
  publisher:
    price: $4,500
  patron:
    price: $8,500
  keystone:
    price: $15,000

date: # how do we handle these? human readable would be nice.
  main: "**May 19-21, 2019, in Portland, Oregon**"
  short: May 19-21, 2019
  tickets_live: "January 2019"
  month: May
  day_one:
    event: Hike
    date: May 18
    summary: If you're in town early, join us for the <a href="/conf/portland/2019/hike/">Hike</a>. Portland has excellent access to the woods right in the city, and we'll be exploring Forest Park and the Hoyt Arboretum.
    icon: hike
  day_two:
    event: Writing Day
    date: May 19
    summary: Join us for the <a href="/conf/portland/2019/writing-day/">Writing Day</a> and Welcome Reception. The first official day of the conference is full of chances to interact with other documentarians.
    icon: writing
  day_three:
    event: Main Conference
    date: May 20-21
    summary: The main days of the conference. We will be running our main track in the ballroom, and the <a href="/conf/portland/2019/unconference/">Unconference</a> in Lola's Room.
    icon: conference

about:
  attendees: 500
  summary:
    "The main presentation track takes place from **May 20-21 (Monday and Tuesday) from 9am to 6pm**.
    We will return to the historic `Crystal Ballroom <http://www.mcmenamins.com/CrystalBallroom>`_, `centrally located <http://goo.gl/maps/D2WrJ>`_ in the heart of Portland.
    During the main event we also run an :doc:`/conf/portland/2019/unconference` downstairs in Lola's Room.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/portland/2019/venue` page."
  location:
    "Crystal Ballroom located at 1332 W Burnside St"
  photos: https://www.flickr.com/photos/writethedocs/albums/72157691507514803

cfp:
  url: https://docs.google.com/forms/d/e/1FAIpQLScCK5qIaRwmn2UouYvtxfrQk56r_X72aliVWLnoGKb69HZuug/viewform
  ends: "31 January, 2019"
  notification: "21 February, 2019"

sponsors:
  keystone:
    - name: google
      link: https://www.google.com
  patron:
    - name: oracle-cloud
      link: https://cloud.oracle.com/iaas
  publisher:
    - name: alexa
      link: https://developer.amazon.com/alexa
    - name: aws
      link: https://aws.amazon.com/
    - name: square
      link: https://squareup.com/
    - name: microsoft
      link: https://developer.microsoft.com
    - name: braintree
      link: https://www.braintreepayments.com/
    - name: twilio
      link: https://www.twilio.com/
    - name: redhat
      link: https://www.redhat.com/
    - name: mozilla-new
      link: https://developer.mozilla.org/
  second:
    - name: salesforce
      link: https://www.salesforce.com
    - name: gitlab
      link: https://gitlab.com
    - name: elastic
      link: https://www.elastic.co
    - name: cisco
      link: https://www.cisco.com
    - name: knowledgeowl
      link: https://www.knowledgeowl.com
    - name: netlify
      link: https://www.netlify.com/wtd
    - name: appian
      link: https://www.appian.com/
    - name: cockroachlabs
      link: https://www.cockroachlabs.com/
    - name: asciidoctor
      link: https://asciidoctor.org/
    - name: redocly
      link: https://redoc.ly
  first:
    - name: support-driven
      link: https://supportdriven.com
    - name: cncf
      link: https://www.cncf.io
    - name: stickermule
      link: https://www.stickermule.com/supports/writethedocs-portland


# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: False
flagticketsonsale: False
flagspeakersannounced: True
flaghasschedule: True
flaghasshirts: True
flagvideos: True
flaglivestreaming: False
flagpostconf: True

# Truthy things that don't change
flaghashike: True
flaghasboat: False
