name: Portland
shortcode: portland
year: 2025
city: Portland
local_area: Oregon
area: North America # European Australian
area_adj: North American
tz: Pacific Time  # PT until March, PST after... :/
email: portland@writethedocs.org
color: green
rgb: 61, 217, 74
hex: 3dd94a
time_format: 12h

photos:
  default:
    - _static/conf/images/headers/2025/grants.jpg
    - _static/conf/images/headers/2025/unconference.jpg
    - _static/conf/images/headers/2025/volunteer.jpg
    - _static/conf/images/headers/2025/writing-day.jpg

buttons:
  top:
    # - text: Date and ticket information
    #   link: /news/welcome
    - text: Sponsor us
      link: /sponsors/prospectus
    - text: Submit a Talk
      link: /cfp
    # - text: See the Schedule!
    #   link: /schedule
    # - text: Buy a Ticket!
    #   link: /tickets
    #- text: See the talks!
    #  link: /speakers
    # - text: Attendee Guide
    #   link: /attendee-guide
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Watch the videos
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpm4FboYSTD1Bs8Yp8k_JvAL
    # - text: Conference recap
    #   link: /news/thanks-recap
  bottom:
    # - text: Welcome to our conference
    #   link: /news/welcome
    - text: Sponsor us
      link: /sponsors/prospectus
    - text: Submit a Talk
      link: /cfp
    # - text: Buy a Ticket!
    #   link: /tickets
    # - text: See the Schedule
    #   link: /schedule
    # - text: See the talks!
    #   link: /speakers
    # - text: Read our guide
    #   link: /attendee-guide
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Conference recap
    #   link: /news/thanks-recap
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72177720308088427
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpm4FboYSTD1Bs8Yp8k_JvAL

tickets:
  concierge:
    price: $750
  corporate:
    price: $650
  independent:
    price: $350
  student:
    price: $100

sponsorship:
  second_draft:
    price: $2,500
  publisher:
    price: $5,000
  patron:
    price: $9,000
  keystone:
    price: $14,000

grants:
  url: https://docs.google.com/forms/d/e/1FAIpQLSf3fGfW_8W1x3oeKeoUpg8ZPLvyY4cQvO5Bii_OTrgW97cLNw/viewform?embedded=true
  ends: 'February 5, 2025'
  notification: 'February 14, 2025'

shirts:
  url: https://shirt.writethedocs.org/
  ends: "May 31, 2025"

date: # how do we handle these? human readable would be nice.
  main: "**May 4-6, 2025**"
  short: May 4-6, 2025
  tickets_live: "December 2024"
  month: May

  # Conference is special for the index to show the combined conference days
  conference:
    event: Speaker Talks
    date: May 5-6
    summary: The main days of the conference. Listen to a diverse panel of speakers share their insights and experience.
    icon: conference

  # These are listed in the schedule
  day_one:
    event: Hike
    date: May 3
    # summary: We encourage you to go on a hike in your own beautiful home town.
    summary: If you're in town early, join us for the Hike. Portland has excellent access to the woods right in the city.
    icon: hike
    dotw: Saturday
  day_two:
    event: Writing Day
    date: May 4
    summary: Kick off the conference with Writing Day and work with fellow documentarians on a project. Followed by the opening reception.
    icon: writing
    dotw: Sunday
    writing_day_time: 9am-5pm
    reception_time: 5-7pm
  day_three:
    event: Conference Day 1
    date: May 5
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Monday
    talk_time: 9am-5pm
    unconference_time: 9:45am-5pm
    social_time: 6:30pm-8:30pm
    icon: conference
  day_four:
    event: Conference Day 2
    date: May 6
    summary: And the conference goes on! More talks and unconference today, along with our Sponsor Expo!
    dotw: Tuesday
    talk_time: 9am-4pm
    job_fair_time: 9-12pm
    unconference_time: 1:35pm-4pm
    icon: conversation
  total_talk_days: 2

about:
  attendees: 400
  social_venue:  TBD
  venue: Revolution Hall
  photos: TBD
  mainroom: Main stage
  unconfroom: Library & Astoria room (1st floor)
  projector_ratio: "16:9"
  job_fair_room: Sponsor area

cfp:
  url: "https://pretalx.com/wtd-portland-2025/cfp" # Open October 6 (Mon) -> 9 weeks to submit
  ends: "January 21, 2025"                         # (Mon) 1 week, to review. It'll take a little longer to announce
  notification: "February 04, 2025"                # (Mon) 8 weeks to write and prepare
  slides_by: "April 28, 2025"                      # (Mon) 1 week before
  preview: "TODO"                                  # Preview URL TODO

unconf:
  url: ""
  date: "All day, Monday, May 5 and Tuesday, May 6"

writing_day:
  url: ""
  date: Sunday, May 4, 9 AM - 5 PM

hike:
  date: Saturday, May 3, 2 PM

sponsors:
  keystone:
    - name: mintlify
      link: https://mintlify.com/?utm_source=writethedocs&utm_medium=referral
      brand: Mintlify
      text: Meet the modern standard for public-facing documentation. Beautiful out of the box, easy to maintain, and built to convert users.
  patron:
    # - name: gitbook
    #   link: https://www.gitbook.com/?ref=writethedocs
    #   brand: GitBook
    #   text: "GitBook combines powerful docs with AI-powered search and insights to give technical teams a single source of truth for their knowledge.
    #          Effortlessly create, surface and improve public and internal documentation that your users and teams will love. "
    # - name: readme
    #   link: https://readme.com/?ref=writethedocs
    #   brand: ReadMe
    #   text: "ReadMe transforms your API docs into interactive hubs that help developers succeed. Help developers make their first call faster, quickly troubleshoot issues along the way, and get insights into API usage to focus your team on the highest-impact improvements."
    # - name: mongodb-new
    #   link: https://www.mongodb.com/?ref=writethedocs
    #   brand: MongoDB
    #   text: "MongoDB's mission is to empower innovators to create, transform, and disrupt industries by unleashing the power of software and data. Built by developers, for developers, MongoDB's developer data platform is a database with an integrated set of related services that allow development teams to address the growing requirements for today's wide variety of modern applications."
    # - name: jetbrains-svg
    #   link: https://jebrains.com/writethedocs
    #   brand: JetBrains
    #   text: "JetBrains is a software development company known for best-of-class integrated development environments (IDEs) like IntelliJ IDEA, PyCharm, and WebStorm. With Writerside, JetBrains brings its expertise to technical writing."
    # - name: zoomin-small
    #   link: https://www.zoominsoftware.com/?vert=Write_The_Docs_Portland&utm_medium=referral&utm_source=WriteTheDocs&utm_campaign=Write_The_Docs_Portland
    #   brand: Zoomin
    #   text: "Zoomin is transforming the way enterprises offer and gain value from their product content.
    #          Our AI-infused content delivery platform lets you deliver knowledge from any source and format to wherever customers look for it, all within a personalized, unified and effortless experience. This radically improved content experience helps users successfully self-serve while deflecting cases away from overburdened support teams. Using proprietary analytics, Zoomin also provides actionable insights that guide decision-making across the enterprise. "
  publisher:
    # - name: jetbrains
    #   link: https://www.jetbrains.com/
    #   brand: JetBrains
    # - name: bloomberg-engineering
    #   link: https://www.bloomberg.com/company/careers/working-here/engineering/
    #   brand: Bloomberg Engineering
    # - name: paligo
    #   link: https://paligo.net/
    #   brand: Paligo
    #   width: 200px
    # - name: stackblitz-svg
    #   link: https://stackblitz.com/
    #   brand: StackBlitz
    # - name: cncf
    #   link: https://www.cncf.io/
    #   brand: Cloud Native Computing Foundation
    # - name: twilio
    #   link: https://www.twilio.com/
    #   brand: Twilio
    # - name: slack
    #   link: https://slack.com/
    #   brand: Slack
  second:
    # - name: nginx
    #   link: https://www.nginx.com/?ref=writethedocs
    #   brand: NGINX
    - name: redocly
      link: https://redoc.ly/
      brand: Redocly
    # - name: netlify-new
    #   link: https://www.netlify.com/?ref=writethedocs
    #   brand: Netlify
    # - name: google
    #   link: https://opensource.google/?ref=writethedocs
    #   brand: Google Open Source
    #   text: "Google believes that open source is good for everyone. By being open and freely available, it enables and encourages collaboration and the development of technology."
    - name: readthedocs
      link: https://about.readthedocs.com/?ref=writethedocs
      brand: Read the Docs
      text: "Read the Docs simplifies software documentation by building, versioning, and hosting of your docs, automatically. Treating documentation like code keeps your team in the same tools, and your documentation up to date."
    # - name: knowledgeowl
    #   link: https://www.knowledgeowl.com?ref=writethedocs
    #   brand: KnowledgeOwl
    # - name: raspberrypi
    #   link: https://www.raspberrypi.com/
    #   brand: Raspberry Pi
    # - name: readthedocs
    # - name: livelike
    #   link: https://livelike.com/
    #   brand: LiveLike
    # - name: openwebdocs-logo
    #   link: https://opencollective.com/open-web-docs
    #   brand: Open Web Docs
    #   width: 150px
    # - name: juniper
    #   link: https://www.juniper.net/
    #   brand: Juniper
    # - name: starburst
    #   link: https://www.starburst.io/
    #   brand: Starburst
  first:
  in_kind:
    # - name: rtd
    #   link: https://readthedocs.com/
    #   brand: Read the Docs

# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: True
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flagscheduleincomplete: True
flaghasshirts: False
flaglivestreaming: False
flagvideos: False
flagpostconf: False
flaghasbadgeflair: False

# Truthy things that don't change
flaghasunconf: True
flaghashike: True
flaghasfood: True
flaghaswritingday: True
flaghaslightningtalks: True
flaghasjobfair: True
flaghasboat: False
