name: Prague

shortcode: prague
year: 2021
city: Prague
local_area: Czech Republic
area: Europe
area_adj: European
tz: CEST
email: prague@writethedocs.org
color: gold
rgb: 253,185,19
hex: fdb913

photos:
  default: _static/conf/images/headers/prague-group.png

buttons:
  top:
    - text: Welcome to our conference
      link: /news/welcome
#    - text: Date and ticket information
#      link: /news/announcing-virtual-conf-dates-tickets
    # - text: Read our conference guide
    #   link: /welcome-wagon
    # - text: See the Schedule!
    #   link: /schedule
#    - text: Buy a Ticket!
#      link: /tickets
    - text: Sponsor us
      link: /sponsors/prospectus
    #- text: Submit a Talk
    #  link: /cfp
    #- text: See the talks!
    #   link: /speakers
    # - text: See the Schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ
  bottom:
     - text: Welcome to our conference
       link: /news/welcome
    # - text: See the Schedule!
    #   link: /schedule
#     - text: Date and ticket information
#       link: /news/announcing-virtual-conf-dates-tickets
     - text: Sponsor the conference
       link: /sponsors/prospectus
    # - text: See the talks!
    #   link: /speakers
#     - text: Buy a Ticket!
#       link: /tickets
    # - text: Prepare with the Welcome Wagon
    #   link: /welcome-wagon
    # - text: See the schedule!
    #   link: /schedule
    # - text: Watch the Live Stream
    #   link: /livestream
    # - text: Browse the photos
    #   link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
    # - text: Watch the videos!
    #   link_absolute: https://www.youtube.com/playlist?list=PLZAeFn6dfHpkBJAPYFrob6gqdiBuePwGJ

tickets:
  corporate:
    price: €125
  independent:
    price: €75
  student:
    price: €25

sponsorship:
  second_draft:
    price: €1,500
  publisher:
    price: €3,500
  patron:
    price: €7,500
  keystone:
    price: €13,500

grants:
  url:
  ends:
  notification:

shirts:
  url:
  ends:

date: # how do we handle these? human readable would be nice.
  main: "**April 25-27, 2021, online**"
  short: Oct 3-5, 2021
  tickets_live: "XXXX 2021"
  month: October
  # Conference is special for the index to show the combined conference days
  conference:
    event: Main Conference
    date: October 4-5
    summary: The main days of the conference. We will be running one main track, and an <a href="/conf/prague/2021/unconference/">Unconference</a>.
    icon: conference
  # These are listed in the schedule
  day_one:
    event: Hike
    date: On your own
    summary: We encourage you to go on a hike in your own beautiful home town.
    #summary: If you're in town early, join us for the Hike. prague has excellent access to the woods right in the city, and we'll be exploring Forest Park and the Hoyt Arboretum.
    icon: hike
    dotw: Saturday
  day_two:
    event: Writing Day
    date: October 3
    summary: Join us for the <a href="/conf/prague/2021/writing-day/">Writing Day</a> and Welcome Reception. The first official day of the conference is full of chances to interact with other documentarians.
    #summary: Join us for the Writing Day and Welcome Reception. The first official day of the conference is full of chances to interact with other documentarians.
    icon: writing
    dotw: Sunday
    writing_day_time: 10:00-18:00
  day_three:
    event: Conference Day 1
    date: October 4
    summary: This is the main event! Hear from lots of interesting folks about all things documentation. We will have talks all day, and unconference sessions running in parallel.
    dotw: Monday
    talk_time: 10:00-18:00
    unconference_time: 9:45-17:00
  day_four:
    event: Conference Day 2
    date: October 5
    summary: And the conference goes on! We are already starting to miss you. |:heart:|
    dotw: Tuesday
    talk_time: 10:00-18:00
    job_fair_time: 9:45-12:00
    unconference_time: 14:15-17:00
  total_talk_days: 2

about:
  attendees: 600
  summary:
    "The main presentation track takes place from **April 26-27 (Monday and Tuesday) from 10:00 to 18:00**.
    During the main event we also run an :doc:`/conf/prague/2021/unconference`."
  venue: "Online conference platform"
  photos:
  mainroom: "Video area"
  unconfroom: "Chat area"
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"

cfp:
  url:
  ends: "February 1, 2021"          # 2 weeks to review and get confirmnations
  notification: "February 15, 2021" # leaves 6 weeks to write and record
  video_by: "March 31, 2021"        # 3 weeks before the conf

unconf:
  url:


sponsors:
  keystone:
  patron:
  publisher:
  second:
  first:


# Things that change over time, listed in order of change
flaglanding: True
flaghassponsors: False
flagcfp: False
flagticketsonsale: False
flagsoldout: False
flagspeakersannounced: False
flagrunofshow: False
flaghasschedule: False
flaghasunconf: False
flaghasshirts: True
flagvideos: False
flaglivestreaming: False
flagpostconf: False

# Truthy things that don't change
flaghashike: False
flaghasboat: False
flaghaswritingday: True
flaghasjobfair: True
flaghasbadgeflair: False
