name: Prague

shortcode: prague # prague australia?
year: 2020
city: Prague
local_area: Czech Republic
area: Europe
area_adj: European
tz: CEST
email: prague@writethedocs.org
color: blue

photos:
  default: _static/conf/images/headers/prague-group.png

buttons:
  top:
     # - text: The conference is moving online
     #   link_absolute: /blog/moving-portland-prague-2020-online/
    - text: Buy a Ticket!
      link: /tickets
    - text: Sponsor us
      link: /sponsors/prospectus
    # - text: Submit a Talk
    #   link: /cfp
    # - text: See the talks!
    #   link: /speakers
#    - text: See the Schedule!
#      link: /schedule
    # - text: Welcome Wagon
    #   link: /welcome-wagon
#    - text: Watch the Live Stream
#      link: /livestream
#     - text: Browse the photos
#       link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
#     - text: Watch the videos!
#       link_absolute: /videos/portland/2020
  bottom:
    - text: Sponsor us
      link: /sponsors/prospectus
     # - text: The conference is moving online
     #   link_absolute: /blog/moving-portland-prague-2020-online/
     # - text: Submit a Talk
     #  link: /cfp
    - text: Buy a Ticket!
      link: /tickets
#    - text: Prepare with the Welcome Wagon
#      link: /welcome-wagon
#    - text: See the schedule!
#      link: /schedule
    # - text: Watch the Live Stream
    #  link: /livestream
#     - text: Browse the photos
#       link_absolute: https://www.flickr.com/photos/writethedocs/albums/72157691507514803
#     - text: Watch the videos!
#       link_absolute: /videos/portland/2020

tickets:
  corporate:
    price: €125
  independent:
    price: €75
  student:
    price: €25

sponsorship:
  second_draft:
    price: €1,500
  publisher:
    price: €3,500
  patron:
    price: €7,500
  keystone:
    price: €13,500

grants:
  url: https://docs.google.com/forms/d/e/1FAIpQLSeMkscbftaTNfr3OS6f5X8xSxJqi1CP3oaYe3jeauzi_uECXg/viewform
  ends: "September 1, 2020"
  notification: "September 14, 2020"

shirts:
  url: https://teespring.com/wtd-prague-2020
  ends: "November 30th"

cfp:
  url: https://pretalx.com/wtd-prague-2020/cfp
  ends: "July 22, 2020"
  notification: "August 14, 2020"

date: # how do we handle these? human readable would be nice.
  main: "**October 18-20, 2020, online**"
  short: Oct 18-20, 2020
  tickets_live: "Summer 2020"
  month: October
  day_one:
    event: Hike
    date: On your own
    summary: In the tradition of WTD Portland we encourage you to go on a hike in your own beautiful home town.
    #summary: If you're in town early, join us for the Hike. Portland has excellent access to the woods right in the city, and we'll be exploring Forest Park and the Hoyt Arboretum.
    icon: hike
    dotw: Saturday
  day_two:
    event: Writing Day
    date: October 18
    summary: Join us for the Writing Day and Welcome Reception. The first official day of the conference is full of chances to interact with other documentarians.
    icon: writing
    dotw: Sunday
  day_three:
    event: Main Conference
    date: October 19-20
    summary: The main days of the conference. We will be running a main track with talks, and an Unconference.
    icon: conference
    dotw: Monday/Tuesday
  total_talk_days: 2

about:
  attendees: 400
  summary:
    "The main presentation track takes place from **October 19-20 (Monday and Tuesday) from 10:00 to 18:00**.
    During the main event we also run an :doc:`/conf/prague/2020/unconference`."
  venue: "Online, platform to be determined"
  mainroom: TBA
  unconfroom: TBA
  projector_ratio: "16:9"
  job_fair_room: "Sponsor area"


sponsors:
  publisher:
  second:
    - name: redhat-new
      link: https://www.redhat.com/
      brand: Red Hat
    - name: elastic
      brand: Elasticsearch
      link: https://www.elastic.co
    - name: knowledgeowl
      link: https://www.knowledgeowl.com
      brand: KnowledgeOwl
      width: 250px
  first:
  media:
    - name: bart
      link: http://www.bartatwork.com
      brand: Bart at work
    - name: techwriter-pl
      link: http://techwriter.pl
      brand: techwriter.pl


# Things that change over time, listed in order of change
flaglanding: False
flaghassponsors: True
flagcfp: False
flagticketsonsale: True
flagsoldout: False
flagspeakersannounced: True
flaghasschedule: False
flagvideos: False
flaglivestreaming: False
flagpostconf: False

# Truthy things that don't change
flaghashike: False
flaghasboat: False
flaghaswritingday: True
flaghasbadgeflair: False
